name: On Push To Main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Changesets Release Flow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Prep Project
        uses: ./.github/composite-actions/node-setup-ubuntu

      - name: Code Checks
        uses: ./.github/composite-actions/code-checks
